name: Android CI to generate release build apk for internal testing
on:
  push:
    branches:
      - master
jobs:
  release:
    if: "contains(github.event.head_commit.message, 'build-apk-now')"
    name: Release apk
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      # 1
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        name: Setup java
        with:
            distribution: 'adopt' # See 'Supported distributions' for available options
            java-version: '8'

      - name: Delete release and tag
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: v1.0.0
      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Delete release and tag
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: v1.0.0

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}
      # 2
      - name: Generate Release APK
        id: generate_apk
        run: ./gradlew assembleRelease

      # 4
      - uses: actions/upload-artifact@master
        id: upload
        with:
          name: 'app-release.apk'
          path: ./app/build/outputs/apk/release/app-release.apk
      # 5
      - name: list file
        run: |
          ls app/build/outputs/apk/release

      - name: Download apk from build
        id: download
        uses: actions/download-artifact@master
        with:
          name: app-release.apk

      - name: Create release and upload apk
        uses: underwindfall/create-release-with-debugapk@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          asset_path: app/build/outputs/apk/release/app-release.apk
          asset_name: ExpenseMonitor.apk
          asset_content_type: application/zip